server:
  port: 8005
  servlet:
    context-path: /pm
spring:
  application:
    name: pm
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  mapper-locations:
    - classpath*:dao/*.xml
    - classpath*:com/**/mapper/*.xml
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: paradise-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: paradise
  key:
    admin: 'paradise:admin'
    resourceList: 'paradise:resourceList'
  expire:
    common: 86400 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /**/swagger-ui.html
      - /**/doc.html
      - /**/swagger-resources/**
      - /**/swagger/**
      - /**/v2/api-docs
      - /**/v2/api-docs-ext
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /**/webjars/springfox-swagger-ui/**
      - /**/actuator/**
      - /**/druid/**
      - /**/admin/login
      - /**/admin/register
      - /**/admin/info
      - /**/admin/logout
      - /**/admin/pass/reset
      - /**/test/**
      - /**/home/**

minio:
  endpoint: http://192.168.199.37:8008 #MinIO服务所在地址
  bucketName: er-oss #存储桶名称
  accessKey: L18S3MC4V2B6W8ZLLP9Y #访问的key
  secretKey: Y+nkVyUgRG9RiiYOJARe7aBS0ighgfZnxbaaHGJN #访问的秘钥
  openUrl: https://yyyd.gaoshan.co:8003
oss:
  secretId: AKIDsa3dyEvKHLJWbQpbBOL3V1awQZWJq7B8 # 提交代码记得忽略 gitignore
  secretKey: y43oa6MQFrPBj24tVu3RqNee6PbcjukQ  # 提交代码记得忽略 gitignore
  appId: 1256237186
  regionName: ap-nanjing
  bucketName: paradise
